version: '2'
  #trigger
services:
  node:
    tty: true # Enables debugging capabilities when attached to this container.
    image: docker.io/bitnami/node:16
    # command: sh -c 'npm install && npm start'
    ports:
      - 3000:3000
    volumes:
      - .:/app
